In [ ]:
#Agenda 
  #implementation of Hands-On of Pandas

In [ ]:
1. Display the top 100 records from the original data frame.
2. Display the last 10 records from the data frame.
3. Display the last record from the data frame.

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Display the top 100 records from the original data frame.
df = pd.read_csv('cc.csv')

In [12]:
df.head(20)

    customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0   7590-VHVEG  Female              0  ...          29.85        29.85     No
1   5575-GNVDE    Male              0  ...          56.95       1889.5     No
2   3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3   7795-CFOCW    Male              0  ...          42.30      1840.75     No
4   9237-HQITU  Female              0  ...          70.70       151.65    Yes
5   9305-CDSKC  Female              0  ...          99.65        820.5    Yes
6   1452-KIOVK    Male              0  ...          89.10       1949.4     No
7   6713-OKOMC  Female              0  ...          29.75        301.9     No
8   7892-POOKP  Female              0  ...         104.80      3046.05    Yes
9   6388-TABGU    Male              0  ...          56.15      3487.95     No
10  9763-GRSKD    Male              0  ...          49.95       587.45     No
11  7469-LKBCI    Male              0  ...          18.95        326.8     No
12  8091-TTVAX    Male              0  ...         100.35       5681.1     No
13  0280-XJGEX    Male              0  ...         103.70       5036.3    Yes
14  5129-JLPIS    Male              0  ...         105.50      2686.05     No
15  3655-SNQYZ  Female              0  ...         113.25      7895.15     No
16  8191-XWSZG  Female              0  ...          20.65      1022.95     No
17  9959-WOFKT    Male              0  ...         106.70      7382.25     No
18  4190-MFLUW  Female              0  ...          55.20       528.35    Yes
19  4183-MYFRB  Female              0  ...          90.05       1862.9     No

[20 rows x 21 columns]

In [4]:
#2. Display the last 10 records from the data frame
df.tail(10)

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
7033  9767-FFLEM    Male              0  ...          69.50      2625.25     No
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7035  8456-QDAVC    Male              0  ...          78.70       1495.1     No
7036  7750-EYXWZ  Female              0  ...          60.65        743.3     No
7037  2569-WGERO  Female              0  ...          21.15       1419.4     No
7038  6840-RESVB    Male              0  ...          84.80       1990.5     No
7039  2234-XADUH  Female              0  ...         103.20       7362.9     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7041  8361-LTMKD    Male              1  ...          74.40        306.6    Yes
7042  3186-AJIEK    Male              0  ...         105.65       6844.5     No

[10 rows x 21 columns]

In [5]:
#Display the last record from the data frame
df.tail(1)

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
7042  3186-AJIEK   Male              0  ...         105.65       6844.5     No

[1 rows x 21 columns]

In [7]:
df.iloc[-1:]

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
7042  3186-AJIEK   Male              0  ...         105.65       6844.5     No

[1 rows x 21 columns]

In [ ]:
1. Now select the rows from 20th index till 200th index (exclusive), and columns from 2nd index till
15th index value.

In [9]:
df.iloc[20:200,2:16]

     SeniorCitizen Partner  ...      StreamingMovies        Contract
20               1      No  ...                  Yes  Month-to-month
21               0     Yes  ...  No internet service        One year
22               0      No  ...  No internet service  Month-to-month
23               0     Yes  ...                   No        Two year
24               0     Yes  ...                   No  Month-to-month
..             ...     ...  ...                  ...             ...
195              0     Yes  ...                   No  Month-to-month
196              0     Yes  ...  No internet service        Two year
197              0      No  ...                  Yes  Month-to-month
198              0     Yes  ...                  Yes        Two year
199              0      No  ...  No internet service  Month-to-month

[180 rows x 14 columns]

In [11]:
df.iloc[20:201]

     customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
20   8779-QRDMV    Male              1  ...          39.65        39.65    Yes
21   1680-VDCWW    Male              0  ...          19.80       202.25     No
22   1066-JKSGK    Male              0  ...          20.15        20.15    Yes
23   3638-WEABW  Female              0  ...          59.90       3505.1     No
24   6322-HRPFA    Male              0  ...          59.60       2970.3     No
..          ...     ...            ...  ...            ...          ...    ...
196  9178-JHUVJ    Male              0  ...          24.10        587.4     No
197  6168-YBYNP    Male              0  ...         111.35      6519.75     No
198  7255-SSFBC    Male              0  ...         112.25      8041.65     No
199  3645-DEYGF    Male              0  ...          20.75        20.75     No
200  9323-HGFWY  Female              0  ...         101.90      2681.15     No

[181 rows x 21 columns]

In [16]:
df1 = df.head()

In [17]:
df1

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [ ]:
1. Now from the churn data frame, try to sort the data by the tenure column according to the
descending order.
2. Fetch all the records that are satisfying the following condition:
a. Tenure>50 and the gender as ‘Female’.
b. Gender as ‘Male’ and SeniorCitizen as 0.
c. TechSupport as ‘Yes’ and Churn as ‘No’.
d. Contract type as ‘Month-to-month’ and Churn as‘Yes’.

In [20]:
#1. Now from the churn data frame, try to sort the data by the tenure column according to the descending order.
data = df.sort_values(by ='tenure',ascending=False)
data

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1672  4737-AQCPU    Male              0  ...          72.10      5016.65     No
193   9680-NIAUV  Female              0  ...         109.70       8129.3     No
4553  5914-XRFQB    Male              0  ...         115.80       8424.9     No
483   5168-MQQCA  Female              0  ...         108.50       8003.8     No
3266  0464-WJTKO  Female              0  ...          20.10      1460.85     No
...          ...     ...            ...  ...            ...          ...    ...
1082  4367-NUYAO    Male              0  ...          25.75                  No
3826  3213-VVOLG    Male              0  ...          25.35                  No
936   5709-LVOEQ  Female              0  ...          80.85                  No
6754  2775-SEFEE    Male              0  ...          61.90                  No
1340  1371-DWPAZ  Female              0  ...          56.05                  No

[7043 rows x 21 columns]

In [21]:
#Tenure>50 and the gender as ‘Female’
df.loc[(df.tenure>50)& (df.gender == 'Female')]

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
15    3655-SNQYZ  Female              0  ...         113.25      7895.15     No
16    8191-XWSZG  Female              0  ...          20.65      1022.95     No
23    3638-WEABW  Female              0  ...          59.90       3505.1     No
30    3841-NFECX  Female              1  ...          96.35      6766.95     No
35    6234-RAAPL  Female              0  ...          99.90       7251.7     No
...          ...     ...            ...  ...            ...          ...    ...
7023  1035-IPQPU  Female              1  ...         103.50       6479.4     No
7028  9281-CEDRU  Female              0  ...          64.10      4326.25     No
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7037  2569-WGERO  Female              0  ...          21.15       1419.4     No
7039  2234-XADUH  Female              0  ...         103.20       7362.9     No

[1022 rows x 21 columns]

In [22]:
#Gender as ‘Male’ and SeniorCitizen as 0
df1 = df.loc[(df.gender =='Male')& (df.SeniorCitizen == 0)]

In [23]:
df1

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1     5575-GNVDE   Male              0  ...          56.95       1889.5     No
2     3668-QPYBK   Male              0  ...          53.85       108.15    Yes
3     7795-CFOCW   Male              0  ...          42.30      1840.75     No
6     1452-KIOVK   Male              0  ...          89.10       1949.4     No
9     6388-TABGU   Male              0  ...          56.15      3487.95     No
...          ...    ...            ...  ...            ...          ...    ...
7027  0550-DCXLH   Male              0  ...          73.35       931.55     No
7033  9767-FFLEM   Male              0  ...          69.50      2625.25     No
7035  8456-QDAVC   Male              0  ...          78.70       1495.1     No
7038  6840-RESVB   Male              0  ...          84.80       1990.5     No
7042  3186-AJIEK   Male              0  ...         105.65       6844.5     No

[2981 rows x 21 columns]

In [24]:
#c. TechSupport as ‘Yes’ and Churn as ‘No’.
df2 = df.loc[(df.TechSupport == 'Yes') & (df.Churn == 'No')]
df2

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
14    5129-JLPIS    Male              0  ...         105.50      2686.05     No
15    3655-SNQYZ  Female              0  ...         113.25      7895.15     No
23    3638-WEABW  Female              0  ...          59.90       3505.1     No
24    6322-HRPFA    Male              0  ...          59.60       2970.3     No
...          ...     ...            ...  ...            ...          ...    ...
7027  0550-DCXLH    Male              0  ...          73.35       931.55     No
7028  9281-CEDRU  Female              0  ...          64.10      4326.25     No
7036  7750-EYXWZ  Female              0  ...          60.65        743.3     No
7038  6840-RESVB    Male              0  ...          84.80       1990.5     No
7042  3186-AJIEK    Male              0  ...         105.65       6844.5     No

[1734 rows x 21 columns]

In [25]:
#Contract type as ‘Month-to-month’ and Churn as‘Yes’.
df3 = df.loc[(df.Contract == 'Month-to-month')& (df.Churn == 'Yes')]
df3

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65        820.5    Yes
8     7892-POOKP  Female              0  ...         104.80      3046.05    Yes
13    0280-XJGEX    Male              0  ...         103.70       5036.3    Yes
...          ...     ...            ...  ...            ...          ...    ...
7018  1122-JWTJW    Male              0  ...          70.65        70.65    Yes
7026  8775-CEBBJ  Female              0  ...          44.20       403.35    Yes
7032  6894-LFHLY    Male              1  ...          75.75        75.75    Yes
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7041  8361-LTMKD    Male              1  ...          74.40        306.6    Yes

[1655 rows x 21 columns]

In [26]:
#1. Use a for loop to calculate the number of customers that are getting the tech support and are male senior citizen
df.shape

(7043, 21)

In [27]:
df2 = df.loc[(df.TechSupport == "Yes") & (df.gender == "Male") & (df.SeniorCitizen == 1)]

In [31]:
c= []
for i in df2.index:
  c.append(i)
print('numbers of Customers:',len(c))

numbers of Customers: 119

In [32]:
df2.shape

(119, 21)

In [33]:
df2

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
57    5067-XJQFU   Male              1  ...         108.45      7076.35     No
72    1891-QRQSA   Male              1  ...         111.60         7099     No
91    2424-WVHPL   Male              1  ...          74.70         74.7     No
273   4716-HHKQH   Male              1  ...         107.05      2172.05     No
382   8204-YJCLA   Male              1  ...          64.80      4732.35     No
...          ...    ...            ...  ...            ...          ...    ...
6601  4909-JOUPP   Male              1  ...         109.70      7898.45     No
6605  7632-MNYOY   Male              1  ...         110.90      7432.05    Yes
6763  7471-MQPOS   Male              1  ...          72.90      5139.65     No
6956  2451-YMUXS   Male              1  ...          64.55       4250.1     No
7007  2274-XUATA   Male              1  ...          63.10      4685.55     No

[119 rows x 21 columns]